### ISSUE TITLE
Carrier should be 433920000 to match arduino sketch library default

### ISSUE THREAD

**Issue by irritanterik** [athombv/node-homey-arduinodriver#1]
Arduino library has default freq. of 433.92 (`#define NRF905_FREQ 433920000UL`), while the signal definition sets the carrier freq. to 433.934 ("carrier": 433934000).

With this signal definition I could not get Homey connected with arduino.
After change signal definition to "carrier": 433920000 it worked.

**Comment by irritanterik** [comment]
bump

**Comment by irritanterik** [comment]
@jeroenvollenbrock is this fixed?

**Comment by jeroenvollenbrock** [comment]
Yes
